```{r}
knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE)
source("../../utils/load_data.R")
library(here)
library(hms)
library(dplyr)
library(forcats)
library(lubridate)
library(stringr)
library(stringi)
library(janitor)
library(explore)
library(ggplot2)
```


Dada la depuración inicial, en el siguiente documento se procede a realizar los ajustes necesarios para enfocar los modelos que se desarrollarán.

```{r}
nf_data <- load_data("INMLCF_no_fatales_debugged_2015_2024_v2.csv", type = "interim")
```

```{r}
colnames(nf_data)
```

```{r}
nf_data <- nf_data %>%
  mutate(across(
    .fns = as.factor                     
  ))
```


```{r}
nf_data |> is.na() |> colSums() %>% sort(decreasing = TRUE) |> data.frame() %>% setNames("na_count")
```
```{r}
nf_data %>% colnames()
```
```{r}
nf_data %>%
  count(ciclo_vital) 
```


### Escolaridad
```{r}
table(nf_data$escolaridad) %>% sort()
```

```{r, echo=FALSE, results='markup'}
nf_data %>%
  count(escolaridad) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = escolaridad, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por escolaridad", x = "", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r, echo=FALSE}
nf_data <- nf_data %>% mutate(
  escolaridad = case_when(
    escolaridad == "Educación básica primaria" ~ "Educación básica primaria y secundaria",
    escolaridad == "Educación básica secundaria o secundaria baja" ~ "Educación básica primaria y secundaria",
    escolaridad == "Doctorado o equivalente" ~ "Educación superior",
    escolaridad == "Educación técnica profesional y tecnológica" ~ "Educación superior",
    escolaridad == "Especialización, maestría o equivalente" ~ "Educación superior",
    escolaridad == "Universitario" ~ "Educación superior",
    escolaridad == "Educación media o secundaria alta" ~ "Educación superior",
    TRUE ~ escolaridad
  )
)
```


```{r, echo=FALSE}
nf_data %>%
  count(escolaridad) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = escolaridad, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por escolaridad", x = "", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

### Agresor


```{r, echo=FALSE}
nf_data <- nf_data %>% mutate(
  agresor_ag = case_when(
    agresor_ag == "Amigo(a)" ~ "Conocido",
    TRUE ~ agresor_ag
  )
)
```

```{r, echo=FALSE}
nf_data <- nf_data %>% filter(agresor_ag %in% c("Pareja","Familiar","Ex-pareja","Conocido")) 
```

```{r, echo=FALSE, results='markup'}
nf_data %>%
  count(agresor_ag) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  # filter(proporcion >= 2) %>%
  ggplot(aes(x = agresor_ag, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3.4) +  # Texto en negrita
  labs(title = "Casos de violencia por presunto agresor", x = "", y = "Frecuencia") +
  theme_minimal()+
  coord_flip() +scale_x_discrete(labels = function(x) str_wrap(x, width = 30))

```

### Escenario del hecho

```{r, echo=FALSE}
nf_data <- nf_data %>% mutate(
  escenario_del_hecho = case_when(
    escenario_del_hecho != "vivienda" ~ "Espacios sociales",
    TRUE ~ escenario_del_hecho
  )
)
```

```{r, echo=FALSE}
nf_data %>%
  count(escenario_del_hecho) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  # filter(proporcion >= 2) %>%
  ggplot(aes(x = escenario_del_hecho, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3.4) +  # Texto en negrita
  labs(title = "Casos de violencia por escenario_del_hecho", x = "", y = "Frecuencia") +
  theme_minimal()+
  coord_flip() +scale_x_discrete(labels = function(x) str_wrap(x, width = 30))
```

```{r}
table(nf_data$def_naturaleza)
```
### Circunstancia del hecho 

```{r}
nf_data <- nf_data %>% filter(def_naturaleza %in% c("Violencia sexual","Violencia interpersonal","Violencia intrafamiliar","Violencia sociopolítica")) 
```

```{r}
nf_data %>% filter(def_naturaleza == "Violencia interpersonal") %>% group_by(def_naturaleza, circunstancia_del_hecho) %>% summarise(n=n())
```
```{r}
nf_data <- nf_data %>% filter(circunstancia_del_hecho != "Bala perdida") 
```


```{r}
nf_data %>%
  count(def_naturaleza) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = def_naturaleza, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3.4) +  # Texto en negrita
  labs(title = "Casos de violencia por contexto del hecho", x = "", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
nf_data %>% filter(def_naturaleza == "Violencia interpersonal") %>% group_by(def_naturaleza, circunstancia_del_hecho) %>% summarise(n=n())
```

```{r}
nf_data %>% filter(pais_de_nacimiento_de_la_victima =="Venezuela") %>% group_by(def_naturaleza) %>% summarise(n=n())
```
```{r}
nf_data %>% filter(pais_de_nacimiento_de_la_victima =="Venezuela") %>% explore()
```


```{r}
nf_data <- nf_data %>% filter(pais_de_nacimiento_de_la_victima =="Colombia") 
```

```{r}
nf_data %>% filter(grupo_mayor_menor_de_edad =="Menor de edad", def_naturaleza == "Violencia sexual") %>% group_by(circunstancia_del_hecho) %>% summarise(n=n()) 
```

```{r}
nf_data %>% explore()
```


```{r}
nf_data %>% count(estado_civil)
```

```{r}
nf_data %>% select(ciclo_vital, estado_civil, escolaridad, ano_del_hecho, mes_del_hecho, dia_del_hecho, departamento_del_hecho_dane, municipio_del_hecho_dane,escenario_del_hecho, agresor_ag )
```


## Temporales
```{r, echo=TRUE}
nf_data$ano_del_hecho <- nf_data$ano_del_hecho %>% as.factor()
```

```{r}
anio <- nf_data %>%
  count(ano_del_hecho) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = ano_del_hecho, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por año", x = "Año", y = "Frecuencia") +
  theme_minimal()
```

```{r}
meses_orden <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
                 "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
mes <- nf_data %>%
  filter(mes_del_hecho != "Sin información") %>% 
  count(mes_del_hecho) %>%
  mutate(
    mes_del_hecho = factor(mes_del_hecho, levels = meses_orden),
    proporcion = n / sum(n) * 100
  ) %>%
  ggplot(aes(x = mes_del_hecho, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",
            fontface = "bold",
            size = 3) +
  labs(title = "Casos de violencia por mes", x = "Mes", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
dia <- nf_data %>%
  filter(dia_del_hecho != "Sin información") %>% 
  count(dia_del_hecho) %>%
  mutate(dia_del_hecho = factor(dia_del_hecho, levels = c("Lunes", "Martes", "Miércoles", "Jueves", 
                "Viernes", "Sábado", "Domingo")),
    proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = dia_del_hecho, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por día", x = "Día", y = "Frecuencia") +
  theme_minimal()
```


```{r}
hora <- nf_data %>%
  count(rango_de_hora_del_hecho_x_3_horas) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = rango_de_hora_del_hecho_x_3_horas, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por hora", x = "Hora", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r, fig.width=11, fig.height=6.5}
(anio | mes ) / (dia | hora)
ggsave("../../reports/bayes/temp_inmlcf.pdf", (anio | mes ) / (dia | hora), width = 14, height = 7)
```

## Caracterización

```{r}
grupo <- nf_data %>%
  count(grupo_de_edad_de_la_victima) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = grupo_de_edad_de_la_victima, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por grupo de edad", x = "Edad", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r}
orden <- c("Primera Infancia", "Infancia", "Adolescencia", "Juventud", "Adultez", "Adulto Mayor")
ciclo <- nf_data %>%
  count(ciclo_vital) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
   mutate(
    ciclo_vital = factor(ciclo_vital, levels = orden)) %>% 
  ggplot(aes(x = ciclo_vital, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por ciclo vital", x = "ciclo_vital", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r,fig.width = 9, fig.height =4}
(grupo | ciclo)
ggsave(filename = "../../reports/bayes/edad.pdf",
       plot = (grupo | ciclo), width = 9, height = 4)
```

## Estado civil y escolaridad


```{r}

esc <- nf_data %>%
  count(escolaridad) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = escolaridad, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por escolaridad", x = "", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r}
estado <- nf_data %>%
  count(estado_civil) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = estado_civil, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3) +  # Texto en negrita
  labs(title = "Casos de violencia por estado civil", x = "", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r,fig.width = 9, fig.height =5}
(estado | esc)
ggsave(filename = "../../reports/bayes/escolaridad.pdf",
       plot = (estado | esc), width = 9, height = 5)
```


```{r}
agresor <- nf_data %>%
  count(agresor_ag) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  filter(proporcion >= 2) %>%
  ggplot(aes(x = agresor_ag, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3.4) +  # Texto en negrita
  labs(title = "Casos de violencia por presunto agresor", x = "", y = "Frecuencia") +
  theme_minimal()
```

```{r}
tipo <- nf_data %>%
  count(def_naturaleza) %>%
  mutate(proporcion = n / sum(n) * 100) %>%
  ggplot(aes(x = def_naturaleza, y = n)) +
  geom_col(fill = "#AE86D3", alpha = 0.8) +  # Color de las barras
  geom_text(aes(label = paste0(round(proporcion, 1), "%")), 
            vjust = -0.2, 
            color = "#4B0082",  # Morado oscuro
            fontface = "bold",
            size = 3.4) +  # Texto en negrita
  labs(title = "Casos de violencia por tipo de violencia", x = "", y = "Frecuencia") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r,fig.width = 8.5, fig.height =4.5}
(tipo | agresor)
ggsave(filename = "../../reports/bayes/tipo.pdf",
       plot = (tipo | agresor), width = 8.5, height = 4.5)
```
```{r}
prop.table(table(nf_data$def_naturaleza, nf_data$grupo_mayor_menor_de_edad), margin = 1)
```
```{r}

prop.table(table(nf_data$def_naturaleza, nf_data$escenario_del_hecho), margin = 1)
```


