---
title: "Untitled"
author: "Ximena Castañeda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


A continuación se presentan las razones de odds estimadas para todas las variables del modelo es importante tener en cuenta que la tabla anterior indica que las categorías de agresor masculino y agresor femenino no dieron significativas, es decir, no se asocian con mayor ni menor probabilidad de recibir atención en salud mental, comparado con el sexo intersexual. Al igual que centro poblado respecto a cabecera municipal. Por lo tanto, la interpretación de odds ratios para estas categorías no es relevante.

Estos resultados indican que entre mujeres con características similares, aquellas que sufrieron violencia física, psicológica y sexual son más propensas a recibir atención en salud mental que las mujeres que sufrieron negligencia y abandono (71%, 91% y 341%), al igual que aquellas mujeres que viven en zona rural dispersa, con una mayor probabilidad relativa de atención del 22% en comparación con mujeres que viven en la cabecera municipal. En contraste, cuando la mujer es cabeza de familia (37% menos propensas) o convive con el agresor (4% menos) es menos propensas a recibir atención, en comparación con casos donde no lo son y no conviven con el agresor, respectivamente. Finalmente, un hallazgo relevante es que las mujeres que fueron hospitalizadas tras el hecho de violencia son 125% más propensas a recibir atención psicológica.

Ahora bien, este modelo obtuvo un **AUC de 0.8727**, menor al modelo anterior. Este resultado brinda la oportunidad de plantear nuevos modelos que logren captar más ampliamente la dinámica del contexto. 