---
title: "Modelo de regresión logístico bayesiano"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modelo de regresión logístico bayesiano

## Base de datos: Ximena

El conjunto de datos Vigilancia Integrada de la Violencia de Género [(Ver)](https://medata.gov.co/dataset/1-026-22-000170) recopila información sobre casos sospechosos de violencia de género en Antioquia reportados al Sistema Nacional de Vigilancia en Salud Pública (SIVIGILA). Esta base de datos está disponible en el portal de datos abiertos MEData, perteneciente a la ciudad de Medellín.

-   **Última actualización:** 20 de septiembre de 2023. **VERIFICAR**

La base contiene 118 variables provenientes del formulario de notificación del SIVIGILA. **Mencionar cantidad de datos inicial**

Estas variables cubren información sobre el reporte, características de la víctima y del agresor, circunstancias del hecho y atenciones en salud.

## Análisis descriptivo: Ximena

Luego del proceso de depuración y limpieza, la base final quedó conformada por 46.373 registros.

-   **Mencionar cuál es la variable de respuesta y que hace parte de un grupo de laboratorios que se le hace a la mujer**

se seleccionó un conjunto de variables relevantes. **Basados en qué poner pruebas no parametricas**

-   **dar una pequeña definición de las predictoras. poner todos los gráficos de las predictoras o solo las importantes y hacer parrafito sobre el comportamiento de los otros**

-   **Poner gráfico de relación con la variable de respuesta**

## Análisis inferencial: Mariana

## Materiales y métodos

### Modelo de Regresión Logística

Para identificar los factores que más influyen en que una mujer víctima de violencia de género reciba atención en salud mental después de ser atendida en urgencias, se utilizó un enfoque cuantitativo basado en un modelo estadístico llamado **regresión logística**.

Este modelo permite estimar la probabilidad de que ocurra un evento con dos posibles resultados: en este caso, que la víctima **reciba** (sí) o **no reciba** (no) atención psicológica tras el hecho de violencia. El modelo analiza diversas características relacionadas con la víctima, el agresor y el contexto, y estima cómo cada una de estas variables influye en dicha probabilidad.

La variable estudiada tiene la forma:

$$
\begin{equation*}    
Y_i=    
\begin{cases}        
1, & \text{víctima \(i\) recibe atención en salud mental} \\        
0, & \text{en caso contrario}    
\end{cases}
\end{equation*}
$$

Cada víctima tiene una probabilidad asignada de recibir atención, basada en sus características, y esta probabilidad se modela como:

$$
Y_i \sim Bernoulli(\theta_i),\text{ para }i=1,2, \dots,\text{46.373}
$$

Para realizar los cálculos de la probabilidad, el modelo transforma esas probabilidades en una escala distinta, llamada **log-odds** (o logit o logaritmo del cociente de probabilidades), que permite relacionar directamente las características observadas con la probabilidad de atención psicológica.

Matemáticamente, la relación se expresa así:

$$
\begin{equation}
Logit(\theta_i) = \ln \left(\frac{\theta_i}{1 - \theta_i}\right) = \mathbf{X} \boldsymbol{\beta}
\end{equation}
$$

Esto indica que el modelo combina todas las características observadas de cada víctima para calcular la probabilidad de que reciba atención en salud mental:

$$
\theta_i = \frac{e^{\mathbf{X} \boldsymbol{\beta}}}{1 + e^{\mathbf{X} \boldsymbol{\beta}}} \quad \quad \text{y} \quad \quad \mathbf{X} \boldsymbol{\beta} = \alpha + \sum_{j=1}^{k} \beta_j x_{ik}.
$$

Donde:

-   $\mathbf{X}$ es la matriz de diseño: reúne las características observadas de cada víctima (edad, tipo de violencia, lugar de los hechos, entre otras).

-   $\boldsymbol{\beta}$ es el conjunto de parámetros: indican el peso de cada una de las características en la probabilidad y son cantidades a estimar.

-   $\alpha$ es el intercepto del modelo.

### Enfoque bayesiano

En este estudio, la estimación de los parámetros del modelo de regresión logística se realizó bajo un enfoque estadístico **Bayesiano**, que combina dos fuentes de información:

-   Información previa sobre los parámetros del modelo (conocida como **distribución a priori**, denotada por $f(\boldsymbol{\beta})$), basada en investigaciones previas o conocimiento experto.

-   Información observada, proveniente de los datos recopilados de las víctimas (representada por la verosimilitud $f(y, \mathbf{X} | \boldsymbol{\beta})$).

Este enfoque permite incorporar el conocimiento previo y obtener estimaciones más robustas, especialmente útil cuando hay incertidumbre o información limitada.

El resultado es la **distribución posterior**, que refleja lo que se sabe sobre los parámetros luego de observar los datos:

$$
f(\boldsymbol{\beta} | y, \mathbf{X}) \propto f(y, \mathbf{X} | \boldsymbol{\beta}) \cdot f(\boldsymbol{\beta})
$$

En términos sencillos, este enfoque entrega una distribución de probabilidades para cada parámetro, mostrando qué tan probable es cada valor después de considerar la información disponible. Esto permite cuantificar la incertidumbre y es especialmente útil en estudios con datos complejos o incompletos, como en salud pública o ciencias sociales.

Para reflejar esta incertidumbre, se asignaron **distribuciones normales poco informativas** a los parámetros, asumiendo que, antes de observar los datos, cada coeficiente podía tomar una amplia gama de valores centrados en cero sin privilegiar ninguno: $\boldsymbol{\beta} \sim N(0,1)$.

Se incluyeron 10 variables predictoras, que dieron lugar a la estimación de 34 parámetros (33 coeficientes y un intercepto).

Como la distribución posterior no se puede calcular directamente, se usaron algoritmos de **Markov Chain Monte Carlo (MCMC)**, un método computacional que permite aproximarla.

El modelo se implementó en el lenguaje $\textit{Stan}$, mediante la librería $\texttt{rstan}$ en $\textit{RStudio}$.

### Razón de odds (odds ratio)

Como se mencionó anteriormente, una forma clara de interpretar los resultados del modelo es a través de la **razón de odds** (odds ratio, OR), que indica cómo una variable influye en la probabilidad de que una víctima reciba atención en salud mental tras un evento de violencia de género.

Los coeficientes $\beta_j$ están expresados en escala logarítmica, por lo que se **transforman con la función exponencial** para facilitar su interpretación:

$$
OR_j = \exp(\beta_j)
$$

La interpretación del odds ratio es sencilla y se realiza de la siguiente manera:

-   Si $\boldsymbol{OR_j > 1}$, la probabilidad de recibir atención aumenta con esa característica.

-   Si $\boldsymbol{OR_j < 1}$, la probabilidad disminuye.

-   Si $\boldsymbol{OR_j = 1}$, la característica no tiene efecto.

Lo anterior es útil para evaluar de qué forma es la influencia de cada característica en la probabilidad. Sin embargo, el valor del odds ratio obtenido se interpreta como cuántas veces más (o menos) probable es que ocurra el evento (recibir atención) en presencia de dicha característica, en comparación con su ausencia o con la categoría de referencia.

A continuación se presentan las razones de odds estimadas para las variables más relevantes del modelo.

**\*\* FALTA TABLA Y RESULTADOS\*\***

### Medidas de desempeño: AUC y curva ROC

**AUC: explicar para qué sirve, cómo se concluye, gráfica y resultado**

Una vez ajustado el modelo de regresión logística, es fundamental evaluar su capacidad para distinguir entre las mujeres que recibieron atención en salud mental y aquellas que no la recibieron.

Para ello, se utiliza una herramienta llamada **curva ROC** (*Receiver Operating Characteristic*) y un valor asociado a ella conocido como **AUC** (*Área Bajo la Curva*).

La **curva ROC** muestra cómo varía el desempeño del modelo según el punto de corte que se use para decidir si una víctima probablemente recibió atención o no. En el gráfico:

-   El eje horizontal representa la tasa de falsos positivos: porcentaje de casos que el modelo predice erróneamente como atendidos.
-   El eje vertical representa la tasa de verdaderos positivos: porcentaje de casos que el modelo identifica correctamente como atendidos.

Cuanto más se acerque la curva a la esquina superior izquierda del gráfico, mejor será la capacidad del modelo para diferenciar entre ambos grupos.

Por su parte, el **AUC** mide el área bajo la curva ROC. Sus valores van de 0 a 1:

-   Un **AUC cercano a 0.5** indica que el modelo no distingue mejor que el azar (como lanzar una moneda).
-   Un **AUC cercano a 1** indica una excelente capacidad para diferenciar correctamente los casos.

Por tanto, el AUC actúa como un resumen numérico de la capacidad del modelo para clasificar correctamente los casos.

#### Resultado del estudio

En este análisis, el modelo obtuvo un **AUC de 0.9088**, lo que refleja una muy alta capacidad predictiva. Es decir, el modelo identifica correctamente, en la gran mayoría de los casos, si una víctima de violencia de género recibió atención psicológica a partir de las características observadas.

La siguiente figura presenta la curva ROC del modelo, que se aproxima visiblemente a la esquina superior izquierda, lo cual evidencia su buen desempeño.

**\*\* FALTA TABLA Y RESULTADOS\*\***

## Conclusiones sobre resultados

Los resultados obtenidos se destaca que factores como la violencia sexual, la hospitalización o algunos niveles asociados al tipo de parentezco de la víctima con el agresor presentaron efectos más fuertes, incrementando la probabilidad de acceso a la atención en salud mental.

Estos hallazgos son claves para diseñar estrategias que mejoren la cobertura y eficacia de los programas de atención, así como para fortalecer políticas públicas que promuevan la denuncia y garanticen el acceso oportuno a los servicios de salud mental, especialmente en poblaciones vulnerables.
