% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{float}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Justificación de la Selección de Variables para el Modelo estadístico para identificar diagnósticos del impacto de la violencia contra la mujer en la salud mental.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Justificación de la Selección de Variables para el Modelo
estadístico para identificar diagnósticos del impacto de la violencia
contra la mujer en la salud mental.}
\author{}
\date{\vspace{-2.5em}2025-09-11}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{echo=}\ConstantTok{FALSE}\NormalTok{)}

\FunctionTok{library}\NormalTok{(here)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## here() starts at C:/Users/Mariana/OneDrive - Universidad Nacional de Colombia/Documentos/Orquideas/Proyecto-Orquideas
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Adjuntando el paquete: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(purrr)}
\FunctionTok{library}\NormalTok{(rstatix)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'rstatix' was built under R version 4.4.3
\end{verbatim}

\begin{verbatim}
## 
## Adjuntando el paquete: 'rstatix'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:stats':
## 
##     filter
\end{verbatim}

\newpage

\section{Introducción}\label{introducciuxf3n}

El presente documento detalla el proceso y la justificación para la
selección de variables predictoras que se utilizarán en el modelo
estadístico que tiene como objetivo, identificar los factores asociados
a si una víctima de violencia de género recibe o no atención en salud
mental (\textbf{\texttt{ac\_mental}}).

La selección se realizó en dos fases: una depuración inicial basada la
calidad de datos y relevancia en el estudio, seguida de una selección
basada en el estudio estadístico de la asociación de algunas posibles
variables predictoras con la variable respuesta de interés.

\subsection{Parte 1: Depuración y selección inicial de
variables}\label{parte-1-depuraciuxf3n-y-selecciuxf3n-inicial-de-variables}

Inicialmente, se contaba con 82 variables asociada a la información
sobre los casos sospechosos de violencia de género que fieron
resultados. Estas 82 variables fueron explicadas de forma más detallada
en el informe de la depuración de la base de datos y en el informe del
análisis descriptivo.

Posteriormente, se realizó una depuración y selección más detallada de
las variables basada en la completitud de las variables y aquellas cuya
relevancia era limitada para el estudio. Así:

\begin{itemize}
\item
  Se descartaron variables con un alto porcentaje de valores faltantes,
  \emph{una de las justificaciones más clara para el alto nivel de
  valores faltantes, era que, para algunas variables no había
  información para todos los años de estudi, pues algunas preguntas
  relacionadas solo se peguntaban en algunas fichas técnicas de relleno
  de las víctimas para años y en algunos no.} Así, una imputación de
  esos datos en esas variables podrían afectar la integridad del
  análisis, pues no son datos propios de las respuestas de los casos
  sospechosos de las víctimas.
\item
  Por otro lado se conservaron variables consideradas relevantes para el
  fenómeno de la violencia de género según los informes sectoriales
  (como el
  \href{https://www.ins.gov.co/buscador-eventos/Informesdeevento/VIOLENCIA\%20DE\%20GENERO\%20INFORME\%20DE\%20EVENTO\%202023.pdf}{Informe
  de evento Violencia de género e intrafamiliar}).
\end{itemize}

A partir de este proceso se construyó una base de datos depurada con
variables que describen información sobre la víctima, el agresor, el
hecho y la atención recibida. y que tienen potencial relevancia
analítica para estudiar los factores asociados a la atención en salud
mental de las víctimas de violencia de género. Estas variables se
describen a continuación:

\begin{verbatim}
##  [1] "origen"                    "consecutive"              
##  [3] "sexo"                      "orient_sex"               
##  [5] "edad_"                     "grupo_edad"               
##  [7] "tip_ss"                    "per_etn"                  
##  [9] "nom_grupo"                 "gp_discapa"               
## [11] "gp_desplaz"                "gp_migrant"               
## [13] "gp_carcela"                "gp_gestan"                
## [15] "gp_indigen"                "gp_pobicfb"               
## [17] "gp_mad_com"                "gp_desmovi"               
## [19] "gp_psiquia"                "gp_vic_vio"               
## [21] "gp_otros"                  "mujer_cabf"               
## [23] "antec"                     "consum_spa"               
## [25] "cod_pais_r"                "pais_residencia"          
## [27] "cod_dpto_r"                "departamento_residencia"  
## [29] "cod_mun_r"                 "municipio_residencia"     
## [31] "dist_esp_r"                "fec_hecho"                
## [33] "def_naturaleza"            "cod_dpto_o"               
## [35] "departamento_ocurrencia"   "cod_mun_o"                
## [37] "municipio_ocurrencia"      "dist_esp_o"               
## [39] "area"                      "zona_conf"                
## [41] "escenario"                 "ambito_lug"               
## [43] "sust_vict"                 "sexo_agre"                
## [45] "conv_agre"                 "fec_not"                  
## [47] "fec_con"                   "cod_dpto_n"               
## [49] "departamento_notificacion" "cod_mun_n"                
## [51] "municipio_notificacion"    "dist_esp_n"               
## [53] "pac_hos"                   "con_fin"                  
## [55] "cbmte"                     "ac_mental"                
## [57] "remit_prot"                "inf_aut"                  
## [59] "evi_mlegal"
\end{verbatim}

Como se ha mencionado, la variable de interés a analizar es
\textbf{Atención en salud mental}, que indica si la víctima recibió o no
atención psicológica tras la identificación del caso.

\begin{verbatim}
## 
##        1        2 
## 47.80056 51.56038
\end{verbatim}

Del total de 862195 mujeres víctimas, el 47.801\% recibió atención en
salud mental, mientras que el 51.56 no accedió a este servicio.

Así, es de interés buscar los factores asociados a dicha atención, con
base en las características personales, del hecho violento y del
agresor.

De esta manera, de la base depurada, se procedió a identificar las
variables con mayor poder predictivo para la atención en salud mental
mediante un análisis de asociación estadística.

Para ello, se aplicó una prueba estadística de asociación para cada
variable cualitativa, con el fin de determinar si existe una relación
significativa entre esa variable y la atención en salud mental
(\texttt{ac\_mental}). La elección de la prueba dependió del número de
categorías de la variable analizada y del tamaño de las frecuencias
observadas en la tabla de contingencia. Esta tabla cruza las dos
variables de interés para mostrar cuántos casos hay en cada combinación
posible de categorías. Las pruebas utilizadas fueron:

\begin{itemize}
\item
  \textbf{Prueba Chi-cuadrado de Pearson:} Para tablas de contingencia
  con frecuencias esperadas altas.
\item
  \textbf{Chi-cuadrado con simulación de Monte Carlo}: utilizada cuando
  las frecuencias esperadas son bajas y la tabla de contingencia tiene
  dimensión mayor a 2x2, por lo que se requiere una mayor precisión en
  los resultados de la prueba
\item
  \textbf{Prueba exacta de Fisher}: utilizada cuando las frecuencias
  esperadas son bajas y la tabla de contingencia tiene dimensión 2x2.
\end{itemize}

Además, se calculó el \textbf{coeficiente V de Cramér}, que cuantifica
la fuerza de la asociación (0 = sin relación, 1 = relación perfecta).

Con base en los resultados de estas pruebas estadísticas, y considerando
la relevancia de cada variable dentro del contexto de la violencia de
género, se tienen como candidatas a seleccionar como variables
predictoras nueve variables que presentaron asociación estadísticamente
significativa con la atención en salud mental (p \textless{} 0,05).
Además, se tuvo en cuenta que tuvieron coherencia con la literatura y
boletines epidemiológicos del Instituto Nacional de Salud (INS)

\begin{longtable}[]{@{}llrrl@{}}
\toprule\noalign{}
variable & prueba & p.value & cramersV & decision \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
def\_naturaleza & Chi-cuadrado & 0.000 & 0.291 & Posible asociacion \\
cod\_dpto\_n & Chi-cuadrado & 0.000 & 0.231 & Posible asociacion \\
sexo\_agre & Chi-cuadrado & 0.000 & 0.151 & Posible asociacion \\
tip\_ss & Chi-cuadrado & 0.000 & 0.149 & Posible asociacion \\
tip\_ss & Chi-cuadrado & 0.000 & 0.149 & Posible asociacion \\
pac\_hos & Chi-cuadrado & 0.000 & 0.123 & Posible asociacion \\
conv\_agre & Chi-cuadrado & 0.000 & 0.111 & Posible asociacion \\
mujer\_cabf & Chi-cuadrado & 0.000 & 0.059 & Posible asociacion \\
consum\_spa & Chi-cuadrado & 0.000 & 0.058 & Posible asociacion \\
gp\_otros & Chi-cuadrado & 0.000 & 0.045 & Posible asociacion \\
orient\_sex & Chi-cuadrado & 0.000 & 0.040 & Posible asociacion \\
per\_etn & Chi-cuadrado & 0.000 & 0.039 & Posible asociacion \\
gp\_pobicfb & Chi-cuadrado & 0.000 & 0.027 & Posible asociacion \\
gp\_migrant & Chi-cuadrado & 0.000 & 0.025 & Posible asociacion \\
gp\_psiquia & Chi-cuadrado & 0.000 & 0.025 & Posible asociacion \\
gp\_vic\_vio & Chi-cuadrado & 0.000 & 0.019 & Posible asociacion \\
gp\_discapa & Chi-cuadrado & 0.000 & 0.017 & Posible asociacion \\
gp\_gestan & Chi-cuadrado & 0.000 & 0.016 & Posible asociacion \\
zona\_conf & Chi-cuadrado & 0.000 & 0.014 & Posible asociacion \\
gp\_desplaz & Chi-cuadrado & 0.000 & 0.013 & Posible asociacion \\
gp\_indigen & Chi-cuadrado & 0.000 & 0.007 & Posible asociacion \\
gp\_carcela & Chi-cuadrado & 0.000 & 0.004 & Posible asociacion \\
gp\_mad\_com & Chi-cuadrado & 0.051 & 0.002 & No asociacion \\
gp\_desmovi & Chi-cuadrado & 0.633 & 0.001 & No asociacion \\
edad\_ & Spearman & 0.000 & NA & Posible asociacion \\
\end{longtable}

\end{document}
