---
title: "Modelo Logístico Bayesiano para Predicción de Atención en Salud Mental"
output:
  pdf_document:
    toc: true
    number_sections: false
knitr:
  opts_chunk:
    echo: false
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Cargar librerías necesarias

```{r}
library(dplyr)
library(ggplot2)
library(purrr)
library(here)
library(tidyr)
library(rstan)
library(bayesplot)
library(pROC)
library(explore)
```


# Lectura y preparación de la base de datos

```{r}
source("../utils/load_data.R")
data_model <- load_data("data_model.csv", type = "processed")

unique(data_model$ac_mental)
```



# Construcción de la matriz de diseño
```{r}
data_model |> is.na() |> colSums() %>% sort(decreasing = TRUE) |> data.frame() %>% setNames("na_count")
```

```{r}
data <- data_model %>% select(c("ac_mental",
                    "edad", "mujer_cabf","def_naturaleza",
                    "area_", "sexo_agre", "parentezco_agresor", 
                    "conv_agre", "pac_hos_" , "escenario", 
                    "grupo_edad","actividad", 
                    "año_not", "tip_ss_"))

data |> is.na() |> colSums() %>% sort(decreasing = TRUE) |> data.frame() %>% setNames("na_count")
```

```{r}
data %>% explore()
```

```{r}
data %>% group_by(ac_mental) %>% summarise(n=n()) %>%
  mutate(proportion = n / sum(n))
```

# Remover NA en las variables a utilizar

```{r}
## Remove missing values
data <-data[!apply(is.na(data), 1, any), ]
```




```{r}
data %>% group_by(ac_mental) %>% summarise(n=n()) %>%
  mutate(proportion = n / sum(n))
```

```{r}
data %>% filter(tip_ss_=="I") %>% group_by(ac_mental) %>% summarise(n=n())
```


## Muestreo estratificado (10,000 observaciones)

```{r}
# Calcular proporciones por categoría de respuesta
prop_categ <- prop.table(table(data$ac_mental))
tam_categ <- round(10000 * prop_categ)

# Realizar muestreo estratificado según proporciones
set.seed(123)
muestra <- data %>%
  split(.$ac_mental) %>%
  map2_df(tam_categ, sample_n)

# Verificar que las proporciones en la muestra se mantengan
prop.table(table(muestra$ac_mental))
```

**Si se eliminan los NA de esas variables, cambia mucho las proporciones de la variable respuesta en la variable respuesta
